"use strict";

La_Playa.prototype.color_schemes =
[
	{
		name:					'glow',
		hue_start:				180,
		hue_shift:				235,
		hue_shift_exponent:		0.5,
		hue2_start:				180,
		hue2_shift:				220,
		hue2_shift_exponent:	0.3,
		lum_part1:				0.35,
		lum_part1_exponent:		0.25,
		lum_part2:				0.65,
		lum_part2_exponent:		5.0,
		saturation:				1.2,
		saturation2:			1.0,
	},
	{
		name:					'glow2',
		hue_start:				180,
		hue_shift:				235,
		hue_shift_exponent:		1.0,
		hue2_start:				160,
		hue2_shift:				40,
		hue2_shift_exponent:	0.2,
		lum_part1:				0.5,
		lum_part1_exponent:		1.0,
		lum_part2:				0.5,
		lum_part2_exponent:		6.0,
		saturation:				1.0,
		saturation2:			1.0,
	},
	{
		name:					'glow3',
		hue_start:				80,
		hue_shift:				690,
		hue_shift_exponent:		0.2,
		hue2_start:				180,
		hue2_shift:				20,
		hue2_shift_exponent:	0.2,
		lum_part1:				0.25,
		lum_part1_exponent:		0.5,
		lum_part2:				0.75,
		lum_part2_exponent:		4.0,
		saturation:				1.0,
		saturation2:			1.0,
	},
	{
		name:					'pseudoglow',
		hue_start:				120,
		hue_shift:				700,
		hue_shift_exponent:		1.65,
		hue2_start:				120,
		hue2_shift:				700,
		hue2_shift_exponent:	0.2,
		lum_part1:				0.25,
		lum_part1_exponent:		1.5,
		lum_part2:				0.75,
		lum_part2_exponent:		4.0,
		saturation:				1.0,
		saturation2:			1.0,
	},
	{
		name:					'green',
		hue_start:				80,
		hue_shift:				40,
		hue_shift_exponent:		1.0,
		hue2_start:				60,
		hue2_shift:				-1200,
		hue2_shift_exponent:	1.0,
		lum_part1:				0.2,
		lum_part1_exponent:		0.5,
		lum_part2:				0.8,
		lum_part2_exponent:		4.0,
		saturation:				1.0,
		saturation2:			1.0,
	},
	{
		name:					'hmmpf',
		hue_start:				240,
		hue_shift:				-180,
		hue_shift_exponent:		2.0,
		hue2_start:				200,
		hue2_shift:				-120,
		hue2_shift_exponent:	2.0,
		lum_part1:				0.75,
		lum_part1_exponent:		1.5,
		lum_part2:				0.25,
		lum_part2_exponent:		8.0,
		saturation:				1.0,
		saturation2:			1.0,
	},
	{
		name:					'lime',
		hue_start:				120,
		hue_shift:				-60,
		hue_shift_exponent:		1.0,
		hue2_start:				210,
		hue2_shift:				-60,
		hue2_shift_exponent:	1.0,
		lum_part1:				0.25,
		lum_part1_exponent:		0.5,
		lum_part2:				0.75,
		lum_part2_exponent:		4.0,
		saturation:				1.0,
		saturation2:			1.0,
	},
	{
		name:					'blue',
		hue_start:				240,
		hue_shift:				-60,
		hue_shift_exponent:		4.0,
		hue2_start:				0,
		hue2_shift:				15,
		hue2_shift_exponent:	1.0,
		lum_part1:				0.5,
		lum_part1_exponent:		0.5,
		lum_part2:				0.5,
		lum_part2_exponent:		6.0,
		saturation:				1.0,
		saturation2:			1.0,
	},
	{
		name:					'mint',
		hue_start:				140,
		hue_shift:				35,
		hue_shift_exponent:		1.0,
		hue2_start:				350,
		hue2_shift:				15,
		hue2_shift_exponent:	1.0,
		lum_part1:				0.5,
		lum_part1_exponent:		0.5,
		lum_part2:				0.5,
		lum_part2_exponent:		6.0,
		saturation:				1.0,
		saturation2:			1.0,
	},
	{
		name:					'puke',
		hue_start:				340,
		hue_shift:				-280,
		hue_shift_exponent:		1.5,
		hue2_start:				160,
		hue2_shift:				50,
		hue2_shift_exponent:	0.2,
		lum_part1:				0.3,
		lum_part1_exponent:		0.1,
		lum_part2:				0.7,
		lum_part2_exponent:		6.0,
		saturation:				1.0,
		saturation2:			1.0,
	},
	{
		name:					'honey',
		hue_start:				20,
		hue_shift:				29,
		hue_shift_exponent:		2.0,
		hue2_start:				220,
		hue2_shift:				-20,
		hue2_shift_exponent:	2.0,
		lum_part1:				0.4,
		lum_part1_exponent:		0.25,
		lum_part2:				0.6,
		lum_part2_exponent:		8.0,
		saturation:				1.0,
		saturation2:			1.0,
	},
	{
		name:					'wine',
		hue_start:				310,
		hue_shift:				-40,
		hue_shift_exponent:		1.0,
		hue2_start:				0,
		hue2_shift:				-320,
		hue2_shift_exponent:	1.0,
		lum_part1:				0.3,
		lum_part1_exponent:		0.75,
		lum_part2:				0.7,
		lum_part2_exponent:		4.0,
		saturation:				2.0,
		saturation2:			2.0,
	},
	{
		name:					'grey',
		hue_start:				30,
		hue_shift:				0,
		hue_shift_exponent:		1.0,
		hue2_start:				30,
		hue2_shift:				-60,
		hue2_shift_exponent:	1.0,
		lum_part1:				0.25,
		lum_part1_exponent:		1.0,
		lum_part2:				0.75,
		lum_part2_exponent:		3.0,
		saturation:				0,
		saturation2:			0,
	},
	{
		name:					'grey bright',
		hue_start:				10,
		hue_shift:				0,
		hue_shift_exponent:		0.02,
		hue2_start:				30,
		hue2_shift:				-60,
		hue2_shift_exponent:	0.02,
		lum_part1:				0.25,
		lum_part1_exponent:		0.15,
		lum_part2:				0.75,
		lum_part2_exponent:		1.5,
		saturation:				0,
		saturation2:			0,
	},
	{
		name:					'grey brighter',
		hue_start:				10,
		hue_shift:				0,
		hue_shift_exponent:		0.02,
		hue2_start:				30,
		hue2_shift:				-60,
		hue2_shift_exponent:	0.02,
		lum_part1:				0.25,
		lum_part1_exponent:		0.05,
		lum_part2:				0.75,
		lum_part2_exponent:		0.75,
		saturation:				0,
		saturation2:			0,
	},
];



La_Playa.prototype.color_scheme_index = localStorage.getItem('lp__color_scheme') === null ? 2 : parseInt(localStorage.getItem('lp__color_scheme'));

var selected_scheme = La_Playa.prototype.color_schemes[La_Playa.prototype.color_scheme_index];

La_Playa.prototype.color_scheme =
{
	hue_start:				selected_scheme.hue_start,
	hue_shift:				selected_scheme.hue_shift,
	hue_shift_exponent:		selected_scheme.hue_shift_exponent,
	hue2_start:				selected_scheme.hue2_start,
	hue2_shift:				selected_scheme.hue2_shift,
	hue2_shift_exponent:	selected_scheme.hue2_shift_exponent,
	lum_part1:				selected_scheme.lum_part1,
	lum_part1_exponent:		selected_scheme.lum_part1_exponent,
	lum_part2:				selected_scheme.lum_part2,
	lum_part2_exponent:		selected_scheme.lum_part2_exponent,
	saturation:				selected_scheme.saturation,
	saturation2:			selected_scheme.saturation2,
};

//La_Playa.prototype.color_scheme = La_Playa.prototype.color_schemes[La_Playa.prototype.color_scheme_index];

La_Playa.prototype.spectrogram_presets =
[
	{
		name:					'slower',
		melt_speed:				0,
		melt_speed_exponent:	1.0,
		base_speed:				0.0025,
		position_speed:			0,
		position_exponent:		1,
		position_factor:		1,
	},
	{
		name:					'slow',
		melt_speed:				0,
		melt_speed_exponent:	1.0,
		base_speed:				0.005,
		position_speed:			0,
		position_exponent:		1,
		position_factor:		1,
	},
	{
		name:					'normal',
		melt_speed:				0,
		melt_speed_exponent:	1.0,
		base_speed:				0.01,
		position_speed:			0,
		position_exponent:		1,
		position_factor:		1,
	},
	{
		name:					'fast',
		melt_speed:				0,
		melt_speed_exponent:	1.0,
		base_speed:				0.02,
		position_speed:			0,
		position_exponent:		1,
		position_factor:		1,
	},
	{
		name:					'faster',
		melt_speed:				0,
		melt_speed_exponent:	1.0,
		base_speed:				0.03,
		position_speed:			0,
		position_exponent:		1,
		position_factor:		1,
	},
	{
		name:					'walze',
		melt_speed:				0.0125,
		melt_speed_exponent:	4.0,
		base_speed:				-0.015,
		position_speed:			0.02,
		position_exponent:		0.5,
		position_factor:		0.98,
	},
	{
		name:					'walze +',
		melt_speed:				0.5,
		melt_speed_exponent:	16.0,
		base_speed:				-0.115,
		position_speed:			0.15,
		position_exponent:		0.5,
		position_factor:		0.98,
	},
	{
		name:					'walze minus',
		melt_speed:				-0.096,
		melt_speed_exponent:	1.8,
		base_speed:				0.008,
		position_speed:			0.220,
		position_exponent:		6.15,
		position_factor:		0.328,
	},
	{
		name:					'walze minus +',
		melt_speed:				-0.425,
		melt_speed_exponent:	1.8,
		base_speed:				-0.0395,
		position_speed:			0.425,
		position_exponent:		7.2,
		position_factor:		0.328,
	},
	{
		name:					'hypertunnel minus',
		melt_speed:				-0.125,
		melt_speed_exponent:	2,
		base_speed:				0.12,
		position_speed:			0.0,
		position_exponent:		1,
		position_factor:		1,
	},
];

La_Playa.prototype.spectrogram_preset_index = localStorage.getItem('lp__spectrogram_preset') === null ? 6 : parseInt(localStorage.getItem('lp__spectrogram_preset'));

var selected_spectrogram_preset = La_Playa.prototype.spectrogram_presets[La_Playa.prototype.spectrogram_preset_index];

La_Playa.prototype.spectrogram_preset_parameters =
{
	melt_speed:
	{
		title:		'Melt Speed',
		min:		-0.5,
		max:		0.5,
		step:		0.0005,
	},
	melt_speed_exponent:
	{
		title:		'Melt Speed Exponent',
		min:		0.0000001,
		max:		32,
		step:		0.05,
	},
	base_speed:
	{
		title:		'Base speed',
		min:		-0.5,
		max:		0.5,
		step:		0.0005,
	},
	position_speed:
	{
		title:		'Position speed',
		min:		-0.5,
		max:		0.5,
		step:		0.0005,
	},
	position_exponent:
	{
		title:		'Position exponent',
		min:		0.0000001,
		max:		32,
		step:		0.05,
	},
	position_factor:
	{
		title:		'Position factor',
		min:		0.005,
		max:		1.0,
		step:		0.0005,
	},
};

La_Playa.prototype.spectrogram_settings =
{
	melt_speed:				selected_spectrogram_preset.melt_speed,
	melt_speed_exponent:	selected_spectrogram_preset.melt_speed_exponent,
	base_speed:				selected_spectrogram_preset.base_speed,
	position_speed:			selected_spectrogram_preset.position_speed,
	position_exponent:		selected_spectrogram_preset.position_exponent,
	position_factor:		selected_spectrogram_preset.position_factor,
};
